language: python
python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - lektor/admin/node_modules

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.4/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version

install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install --editable .[test]
  - travis_retry make build-js

script: make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
